---
# Create a cron to import the most recent tests from aria-at
- name: Set a cron job to build and import latest test versions from aria-at
  cron:
    name: "import latest aria-at tests"
    minute: "15"
    job: "curl -X POST https://{{fqdn}}/api/test/import"
  when: deployment_mode != 'development'

- name: Set a cron job to build and import latest test versions from aria-at in development
  cron:
    name: "import latest aria-at tests"
    minute: "15"
    job: "curl -X POST http://localhost:5000/api/test/import"
  when: deployment_mode == 'development'

- name: Ensure proper permissions for application_user on db_dumps directory
  become: yes
  block:
    - name: Ensure the db_dumps directory exists
      file:
        path: /home/{{application_user}}/db_dumps
        state: directory
        owner: '{{application_user}}'
        group: '{{application_user}}'
        mode: '0755'

    - name: Ensure application_user has write permissions on the db_dumps directory
      file:
        path: /home/{{application_user}}/db_dumps
        owner: '{{application_user}}'
        group: '{{application_user}}'
        mode: '0775'
  when: deployment_mode == 'staging' or deployment_mode == 'production'

# Create a cron to dump the database in staging and production (run every day at 00:00)
- name: Set a cron job to create a new database dump
  cron:
    name: "create new database dump"
    hour: "0"
    minute: "0"
    job: "curl -X POST https://{{fqdn}}/api/database/dump"
  when: deployment_mode == 'staging' or deployment_mode == 'production'

# Create a cron to clean up the database dumps folder in staging and production (run every day at 00:05)
- name: Set a cron job to clean up the database dumps folder
  cron:
    name: "clean up the database dumps folder if necessary"
    hour: "0"
    minute: "5"
    job: "curl -X POST https://{{fqdn}}/api/database/cleanFolder"
  when: deployment_mode == 'staging' or deployment_mode == 'production'
