---
- name: Ensure apt keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Add software repository keys
  get_url:
    url: '{{ item.url }}'
    dest: '{{ item.dest }}'
    mode: '0644'
  become: yes
  with_items:
    - {
        url: 'https://dl.yarnpkg.com/debian/pubkey.gpg',
        dest: '/etc/apt/keyrings/yarn.asc'
      }
    - {
        url: 'https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key',
        dest: '/etc/apt/keyrings/nodesource.asc'
      }

- include_tasks: upgrade.yml

- name: Add software repositories
  apt_repository:
    state: present
    repo: '{{item}}'
    update_cache: True
  become: yes
  with_items:
    - deb [signed-by=/etc/apt/keyrings/yarn.asc] https://dl.yarnpkg.com/debian/ stable main
    - deb [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_{{ nodejs_major_version }}.x nodistro main

- name: Install packages
  apt:
    name:
      - nodejs
      - yarn
    state: present
  become: yes

- name: Check if Node exists
  command: node --version
  register: new_node_version

- name: Show status of nodejs installation
  debug: msg="{{ new_node_version.stdout }}"

- name: Check if npm exists
  command: npm --version
  register: npm_version

- name: Show status of nodejs installation
  debug: msg="{{ npm_version.stdout }}"
