---
- name: Ensure apt keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Add software repository keys
  shell: |
    curl -fsSL {{ item.url }} | gpg --dearmor -o {{ item.dest }}
  args:
    creates: '{{ item.dest }}'
  become: yes
  with_items:
    - {
        url: 'https://dl.yarnpkg.com/debian/pubkey.gpg',
        dest: '/etc/apt/keyrings/yarn.gpg'
      }
    - {
        url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key',
        dest: '/etc/apt/keyrings/nodesource.gpg'
      }

- include_tasks: upgrade.yml

- name: Add software repositories
  apt_repository:
    state: present
    repo: '{{item}}'
    update_cache: True
  become: yes
  with_items:
    - deb [signed-by=/etc/apt/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main
    - deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x buster main

- name: Install packages
  apt:
    name:
      - nodejs
      - yarn
    state: present
  become: yes

- name: Check if Node exists
  command: node --version
  register: new_node_version

- name: Show status of nodejs installation
  debug: msg="{{ new_node_version.stdout }}"

- name: Check if npm exists
  command: npm --version
  register: npm_version

- name: Show status of nodejs installation
  debug: msg="{{ npm_version.stdout }}"
