- name: Check if Node exists
  shell: |
    if ! node --version; then
      echo "Node.js is not installed"
    fi
  register: node_version
  ignore_errors: true

- name: Show status of nodejs installation
  debug: msg="{{ node_version.stdout }}"

- name: Remove legacy Node.js and Yarn repos
  apt_repository:
    state: absent
    repo: '{{item}}'
    update_cache: False
  become: yes
  with_items:
    - deb https://deb.nodesource.com/node_14.x buster main
    - deb https://deb.nodesource.com/node_18.x buster main
    - deb https://dl.yarnpkg.com/debian/ stable main

- name: Remove Node.js if not version {{ nodejs_major_version }}
  apt:
    name: nodejs
    state: absent
  become: yes
  when: 'node_version.stdout is not match("v" ~ nodejs_major_version ~ "[.]")'
