name: 'Setup Test Environment'
description: 'Sets up Node.js, PostgreSQL, and initializes the test database'

runs:
  using: 'composite'
  steps:
    - name: Install NodeJS 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn

    - name: Setup PostgreSQL
      shell: bash
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get purge -y postgresql\*
        sudo apt-get autoremove -y
        sudo rm -rf /var/lib/postgresql/
        sudo rm -rf /etc/postgresql/
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        sudo apt-get -y update
        sudo apt-get -y install postgresql-12 postgresql-client-12
        sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
        sudo pg_ctlcluster 12 main restart

    - name: Setup database
      shell: bash
      run: |
        yarn --frozen-lockfile
        npx patch-package
        source config/test.env
        sudo -u postgres createdb ${PGDATABASE}
        sudo -u postgres psql -c "CREATE ROLE ${PGUSER} WITH LOGIN PASSWORD '${PGPASSWORD}'"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${PGDATABASE} to ${PGUSER};"
        yarn sequelize:test db:migrate
        yarn sequelize:test db:seed:all
        yarn workspace server db-import-tests:test -c "${IMPORT_ARIA_AT_TESTS_COMMIT_1} ${IMPORT_ARIA_AT_TESTS_COMMIT_2} ${IMPORT_ARIA_AT_TESTS_COMMIT_3} ${IMPORT_ARIA_AT_TESTS_COMMIT_4}"
        yarn workspace server db-import-tests:test
        yarn workspace server db-populate-sample-data:test
