const COLLECTION_JOB_STATUS = {
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  ERROR: 'ERROR',
  CANCELLED: 'CANCELLED'
};

const UPDATE_EVENT_TYPE = {
  COLLECTION_JOB: 'COLLECTION_JOB',
  GENERAL: 'GENERAL',
  TEST_PLAN_RUN: 'TEST_PLAN_RUN',
  TEST_PLAN_REPORT: 'TEST_PLAN_REPORT'
};

const isJobStatusFinal = status =>
  status === COLLECTION_JOB_STATUS.COMPLETED ||
  status === COLLECTION_JOB_STATUS.CANCELLED ||
  status === COLLECTION_JOB_STATUS.ERROR;

module.exports = {
  COLLECTION_JOB_STATUS,
  isJobStatusFinal,
  UPDATE_EVENT_TYPE
};
