name: Version Bump and Changelog Update

on:
  push:
    branches:
      - releases
    paths-ignore:
      - package.json
      - CHANGELOG.md

jobs:
  version-changelog-update:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install NodeJS 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 0
          preset: conventionalcommits
      - name: Pull changes from the development branch
        run: |
          git config --global pull.rebase false
          git pull origin development
      - name: Update development with version bump from CHANGELOG.md and package.json
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git push origin HEAD:development
